### ISSUE TITLE
Feature request: Show number of used cores

### ISSUE THREAD

**Issue by FabioRosado** [coiled/feedback#108]
Val mentioned that it would be good to check the number of cores that a user has used so far, something similar to the message we send when a user requests more cores than the ones that are available.

```
worker_count_requested={'message': 'Requested core count is beyond user limits', 'request': '96', 'active': '18', 'limit': '100'}
```

We could add a command to the API to get this count and perhaps add it to the frontend?

**Comment by jrbourbeau** [comment]
That seems like a reasonable request. We might provide something like a `coiled.info()` method which prints out the number of used cores, core limit, number of GPUs, GPU limit, coiled version, dask & distributed version, etc. This could also be a good opportunity to utilize `rich` for nice outputting.

**Comment by FabioRosado** [comment]
That seems like a great idea, I was looking at the rich docs and I'm curious about the tables and text formatting! 
If everybody thinks this is a good idea, I'll add it to my to-do list when I touch the CLI

**Comment by jrbourbeau** [comment]
> I'll add it to my to-do list

That sounds great, thanks @FabioRosado! FWIW when thinking about what content to add, I'm hoping `coiled.info()` can provide both

- A useful view for users of their Coiled usage and configuration
- A good first place to check for common things that come up when debugging (e.g. "Which version of Dask are you using?")

> I was looking at the rich docs and I'm curious about the tables and text formatting!

🎉

**Comment by ian-r-rose** [comment]
> That seems like a great idea, I was looking at the rich docs and I'm curious about the tables and text formatting!

This sounds like a great idea. I'd add that if you are in a notebook setting, you can produce an HTML table/other markup for nicer reading.

**Comment by dantheman39** [comment]
There should probably also be a spot for this on the clusters dashboard in the frontend

**Comment by FabioRosado** [comment]
Do we want to show how many cores a user has used only or do you think it's useful to add a separate count as well? One for all active clusters and other for all the active jobs?

**Comment by jrbourbeau** [comment]
I can see both clusters and jobs both being useful. Though honestly I'm not sure how jobs tie into our current resource limit system. Is it 100 cores total, 100 cores for clusters and jobs each, or something else?

**Comment by necaris** [comment]
:+1: to showing both. Right now we give them 100 cores total (with a 10% graceful extension factor on clusters).

**Comment by FabioRosado** [comment]
Awesome thank you for the help, I'll add both 👍

**Comment by dantheman39** [comment]
Excited for this and can see it being very useful.

But could we solicit more explicit method / api names? "info" is very generic.

**Comment by dantheman39** [comment]
Closed by https://github.com/coiled/cloud/pull/1721
