### ISSUE TITLE
Non-private software environment is private on dockerhub

### ISSUE THREAD

**Issue by rubenvdg** [coiled/feedback#109]
If I set Docker Hub under Container Registry Options and make a **public** conda environment with coiled, it becomes a **private** repo on my Docker Hub. Is this expected behavior?

Problem is that I'm using a private free-tier account on Docker Hub, which only allows for 1 private repo. If you exceed this, the repos become unavailable. As a consequence, I catch the following when making a new cluster:

```
ValueError: Unable to create cluster: Getting image source signatures
error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]localhost/6be24e83-8b3e-40ca-af71-15f67e53aee9:latest" to "docker://rvdgeer/ruben-van-de-geer9-dask-env-test:6be24e83-8b3e-40ca-af71-15f67e53aee9": Error trying to reuse blob sha256:f5600c6330da7bb112776ba067a32a9c20842d6ecc8ee3289f1a713b644092f8 at destination: Error checking whether a blob sha256:f5600c6330da7bb112776ba067a32a9c20842d6ecc8ee3289f1a713b644092f8 exists in docker.io/rvdgeer/ruben-van-de-geer9-dask-env-test: errors:
denied: **requested access to the resource is denied**
error parsing HTTP 401 response body: unexpected end of JSON input: ""
```

**Comment by FabioRosado** [comment]
Thank you for the questions, we have recently changed a few things about how the software environments are created and perhaps this is the reason why the uploaded image is being set as private.  Let me test things out on my end.

**Comment by FabioRosado** [comment]
Ruben, could you give me more details on how you were trying to build your conda environment?  I've tried to create a software environment with:

```
coiled.create_software_environment(name="soft-env", conda=["dask"])
```

This creates a public repository on docker hub. Even if passing `private=True` it creates a public one, so I am unable to reproduce this

**Comment by rubenvdg** [comment]
Strange. I did:

```
import coiled

coiled.create_software_environment(
    name="new-docker-test",
    container="rvdgeer/dask-base:latest",
    private=True
)
cluster = coiled.Cluster(
    name="new-cluster",
    software="new-docker-test",
)
```

and I end up with:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/37443208/107982651-ba038c80-6fc4-11eb-88c2-c7c28cce9cc7.png">

Not a big deal though, but unexpected nonetheless.

**Comment by rubenvdg** [comment]
@FabioRosado As you mentioned on Slack, this is due to my default privacy settings on Docker Hub being set to "private". Thanks for the feedback!
