### ISSUE TITLE
Can't create a cluster with a different scheduler image

### ISSUE THREAD

**Issue by ericdill** [coiled/feedback#11]
Trying to create a new cluster (mostly just to use a different image as a result of #10), results Django spitting an error to the browser
![image](https://user-images.githubusercontent.com/6223243/82912871-93d02500-9f3b-11ea-8dc3-f04c8c8e390b.png)

Which, I guess, means that there's some mapping from one of these fields (probably name) to Fargate Task Definitions. Not sure how best to expose something like Task Definition creation to the user as it's pretty hairy to get in there and configure a definition. Though, once I can deploy this into my own AWS account, I can create a task definition and then just link them appropriately.

**Comment by necaris** [comment]
@ericdill Thank you for this! Any chance you happened to capture a screenshot of which values you put into the form to get this error?

**Comment by ericdill** [comment]
![image](https://user-images.githubusercontent.com/6223243/82913845-ccbcc980-9f3c-11ea-891a-7c0c2100a857.png)

**Comment by ericdill** [comment]
err those were ericdill/ds-nb:0.1.9, but i doubt that's the problem here

**Comment by ericdill** [comment]
Oh.. I had to explicitly set the GB in the scheduler memory

**Comment by necaris** [comment]
@ericdill Thanks! Looks like we need more validation / to expose the actual error better here

**Comment by mrocklin** [comment]
Previously @seanfarley suggested that we provide a dropdown of valid values
for Fargate.  I think that I shot down that idea in the past because it'll
fail once we get to arbitrary node sizes with ECS-on-EC2.  Maybe that was a
bad move though and we should provide a whitelist of valid values until
then.

**Comment by ericdill** [comment]
I think the only problem here is the need to specify in `GiB`. Seems like it would be fair to just ask the user to provide input that is assumed to be in GiB. Is anyone _not_ doing that anyway?

**Comment by shughes-uk** [comment]
no longer an issue
