### ISSUE TITLE
worker logs appear to be broken

### ISSUE THREAD

**Issue by kpasko** [coiled/feedback#110]
Trying to look at individual worker logs returns error - 

No account named "dashboard" was found

**Comment by FabioRosado** [comment]
Hello @kpasko  thank you for your message. How are you trying to look at the worker logs?

**Comment by kpasko** [comment]
I am going through the dashboard, then info, then logs

**Comment by FabioRosado** [comment]
Thank you on your logs url does it look something like this? `https://cloud.coiled.io/fabiorosado/clusters/5658/logs` ?

**Comment by FabioRosado** [comment]
Keith and I had a great meeting today - the issue that Keith experienced is from the logs in the `info` tab inside the client dashboard (`https://cloud.coiledhq.com/<user>/clusters/<cluster>/dashboard`). 

I've installed the `jupyter-server-proxy` dependency locally, and I can see the logs if I go to the cluster dashboard URL `http://ec2-18-217-134-6.us-east-2.compute.amazonaws.com:8787` but going through the site, it shows a "refused to connect" message.

The console log message contains:

```
Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'deny'
```

**Comment by jrbourbeau** [comment]
If I recall correctly, we're not yet redirecting the worker dashboard pages through the Coiled proxy. cc @marcosmoyano @ian-r-rose

**Comment by marcosmoyano** [comment]
@jrbourbeau that is correct yes

**Comment by shughes-uk** [comment]
bug is long fixed
