### ISSUE TITLE
Cluster.close does not seem to close the cluster when using Azure

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#113]
This isn't a big deal since presumably things will be cleaned up in 20 minutes, but calling cluster.close does not seem to trigger closing the cluster when using the Azure backend.  Pressing the Stop button also does not seem to trigger a close.

![image](https://user-images.githubusercontent.com/306380/108571629-36081800-72d6-11eb-874d-c4eb41aacaf2.png)

**Comment by mrocklin** [comment]
A few days later, it is still stopping

![image](https://user-images.githubusercontent.com/306380/108853966-f038a180-75ac-11eb-8a75-752ebf3539a6.png)

This causes some anxiety on my/a user's part, just because I'm afriad that I've racked up a few hundred dollars in costs

**Comment by shughes-uk** [comment]
azure support deprecated
