### ISSUE TITLE
Accelerate Cluster startup on GCP

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#115]
Creating a cluster on GCP takes around 3 minutes.  I imagine that this is going to be a slow-burning issue, but we'll probably want to look into accelerating this in the future.

```python
In [9]: time cluster = coiled.Cluster(software="play", n_workers=5)
Creating Cluster. This takes about a minute ...Checking environment images
Valid environment image found
CPU times: user 6.08 s, sys: 851 ms, total: 6.93 s
Wall time: 3min 10s
```

**Comment by necaris** [comment]
@mrocklin does this happen _every_ time you create a cluster, or just the first time? @selshowk mentioned that the way things are currently built, the first time will be slower.

**Comment by mrocklin** [comment]
This was not the first time I created a cluster

**Comment by ntabris** [comment]
GCP cluster start times (in the stress test we're running) are now around 2.25-2.5 minutes.

**Comment by shughes-uk** [comment]
Worth clarifying that our instance boot times are now about as fast as they will be, and the biggest gains will be had in future by figuring out how to pull/extract software environments faster
