### ISSUE TITLE
optuna notebook fails:  Can't instantiate abstract class DaskStorage with abstract methods

### ISSUE THREAD

**Issue by murphyk** [coiled/feedback#119]
I am running https://cloud.coiled.io/examples/jobs/optuna.
In the cell 'Train with Optuna' I get this error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-96c3d35abb5d> in <module>
      4 
      5 # Create Dask-compatible Optuna storage class
----> 6 storage = dask_optuna.DaskStorage()
      7 
      8 # Run 500 optimizations trial on our cluster

TypeError: Can't instantiate abstract class DaskStorage with abstract methods get_study_directions, set_study_directions, set_trial_value
```

**Comment by deepakagrawal** [comment]
@murphyk Did you figure out what was causing this issue?

**Comment by ian-r-rose** [comment]
Thanks for the ping on this @deepakagrawal . The issue was a version mismatch -- it should be fixed now, are you still seeing issues?

**Comment by shughes-uk** [comment]
This is quite stale and we no longer maintain these specific examples

**Comment by ncclementi** [comment]
For reference this is an updated example https://docs.coiled.io/user_guide/examples/dask-optuna-hpo.html
