### ISSUE TITLE
List cluster info in `cloud` repr

### ISSUE THREAD

**Issue by ericdill** [coiled/feedback#12]
I was surprised to find out that cluster lifetime is not tied to kernel lifetime. This meant that I had 3 clusters sitting around idle that I didn't even know about. I think there's a larger discussion to have here around what the expectation is around user management of clusters. When I'm sitting in a notebook doing some interactive data exploration / model building / etc., I'd expect that restarting the jupyter notebook terminates the kernel. This is, generally speaking, how the Spark world works and also how dask-gateway handles clusters too. Broadly, I'd be curious to hear about the separation of kernel lifecycle from cluster lifecycle and how best to keep an eye on your clusters. It can be super expensive to accidentally leave a cluster running when you didn't realize it was still running.

One possible way to improve the situation would be to add cluster metadata to the cloud repr so that it lists the cluster name, typename, number of workers, size of each worker.
![image](https://user-images.githubusercontent.com/6223243/82932366-54630200-9f56-11ea-9aec-8295ef6861ba.png)

**Comment by mrocklin** [comment]
The intent is for cluster lifetime to be tied to kernel lifetime short term by default.  The fact that this isn't true is currently a bug.

> It can be super expensive to accidentally leave a cluster running when you didn't realize it was still running.

They should shut off automatically after 20 minutes of inactivity.  This is also currently not running smoothly though :)

In short.  Totally agreed.  Working on it actively.  There is a biggish internal rewrite happening now.

> One possible way to improve the situation would be to add cluster metadata to the cloud repr so that it lists the cluster name, typename, number of workers, size of each worker.

Nice idea.  We were planning to add this information into a dashboard on the webpage, but adding a summary here seems like a great idea.

**Comment by ericdill** [comment]
> The intent is for cluster lifetime to be tied to kernel lifetime short term by default. The fact that this isn't true is currently a bug.

Ah, it's possible that this is due to some short-term pecularities of my own infrastructure. I'm currently building out a simple jupyterhub stack on AWS that's launching user notebooks on Fargate. When I kill the jupyterhub process, it also kills the Fargate containers. And when those Fargate containers have a live coiled dask cluster, I suspect that the abrupt termination does not allow for the Python process to send the "terminate your cluster" signal off to coiled

**Comment by mrocklin** [comment]
Perhaps.  In that case the clusters should shut themselves down within 20
minutes.  They aren't currently doing this (bug on our side).

**Comment by shughes-uk** [comment]
widget repr solved this
