### ISSUE TITLE
How are cores counted? "Requested core count is beyond user limits"

### ISSUE THREAD

**Issue by rubenvdg** [coiled/feedback#124]
If I make a cluster by using:

```
import coiled
cluster = coiled.Cluster(
    name="clustertje",
    n_workers=80,
    worker_cpu=2,
    worker_memory="16 GiB"
)
```

I catch `Exception: worker_count_requested={'message': 'Requested core count is beyond user limits', 'request': '320', 'active': '2', 'limit': '200'}`. 

I would expect that my requested core count is 160 (<200). How is it 320?

**Comment by rubenvdg** [comment]
Follow up question:

If I do:

```
import coiled
cluster = coiled.Cluster(
    name="cluster",
    n_workers=50,
    worker_cpu=2,
    worker_memory="16 GiB"
)
```

I end up with 25 workers:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/37443208/109813142-3e911480-7c2d-11eb-94e3-a1f04b95b9a4.png">

Is this just a matter of non-consistent terminology? What is a "worker" in coiled terminology?

**Comment by FabioRosado** [comment]
Hello Ruben thank you for the question, we currently count the core numbers as the sum of all running and pending schedulers cpus, plus the  worker count times cpu requested. We also include the number of cpus that jobs and notebooks take.

Soon we will add a card on the dashboard that will show you how many cores have you used so far and we are adding a command to display the core usage as well.

Although there might be an issue here, please bear with me as I check something 👍

**Comment by mrocklin** [comment]
Given the response in the exception my guess is that you have another
cluster running.  You should be able to view all running clusters and stop
idling ones on the dashboard available at cloud.coiled.io .  Idle clusters
should clean themselves up after 20 minutes of inactivity.

**Comment by rubenvdg** [comment]
Thanks. I did stop all clusters in the console before. But in hindsight I was probably too impatient (and they were still being teared down).

**Comment by FabioRosado** [comment]
Hello Ruben, I just wanted to give you an update about this. The cores are now counted as you would expect - we have also added a core usage table to the UI and a `list_core_usage()` command that will show you a nice table with your current usage.

I am closing this issue, but please feel free to open or create a new one if you encounter any issues
