### ISSUE TITLE
Cluster initialization fails due to an incompatible/old version of the "rich" package

### ISSUE THREAD

**Issue by hristog** [coiled/feedback#127]
Hello,

I was trying out the quick start example and ran into the following:
```python
~/.local/lib/python3.7/site-packages/coiled/cluster.py in _start(self)
    161     async def _start(self):
    162         console = Console()
--> 163         with console.status(
    164             "[bold green] Creating Cluster. This takes about a minute..."
    165         ):

AttributeError: 'Console' object has no attribute 'status'
```
whilst only having executed:
```python
import coiled
cluster = coiled.Cluster(n_workers=10)
```
The solution for me was to install the latest version of `rich`, namely `rich-9.13.0`. The previous one I'd had apparently was `rich-6.1.2`.

Thanks!

**Comment by FabioRosado** [comment]
Hello @hristog thank you for reporting this to us.
We specify `rich` as a requirement but no minimum version, I will update this so we will require any version of `rich` that has the `Console.status` so this shouldn't happen in the future.

Again thank you for the report and for the help figuring out the issue!

**Comment by hristog** [comment]
HI @FabioRosado, thanks for confirming!
I'll leave it up to you to close this issue, once the minimum requirement for `rich` has been set.

Thanks for your time!

**Comment by FabioRosado** [comment]
My pleasure! I will leave this issue open until we release coiled 0.0.38 just in case other users might hit the same issue as you

**Comment by FabioRosado** [comment]
We have released a new version of coiled which sets a minimum version of rich. I am going to close this issue now, but if you encounter any issues feel free to create a new issue

**Comment by hristog** [comment]
Thanks again!
