### ISSUE TITLE
`rich` and Spyder don't play well together

### ISSUE THREAD

**Issue by necaris** [coiled/feedback#129]
`rich` appears to detect Spyder's IPython window as a Jupyter environment, and spews lots of `rich.jupyter.JupyterRenderable`s at the user. I wonder if people using VS Code's IPython window are going to run into this too?

**Comment by FabioRosado** [comment]
This will be fixed on the next release of Coiled 0.0.39. The changes done upstream to rich still cause some unexpected behaviour with Spyder, mainly the message "Starting cluster this might take a while" keeps being printed on a new line until the cluster creation is done, which isn't ideal. I would advocate for keeping our fix in place.
