### ISSUE TITLE
Enhancement request: improve docs & help for CLI `coiled install`

### ISSUE THREAD

**Issue by jgawad-nlmk** [coiled/feedback#131]
Hi guys,

You might consider improving documentation of `coiled install`, which is pretty much unclear at the moment. 

The required argument to `coiled install` is COILED_URI, but:
- there is no explanation what its value could be or should be,
- the name of the argument includes "URI", which (wrongly?) suggests it should follow URI generic syntax (scheme, path, etc.),
- it appears this COILED_URI could be in format "[coiled_user/]software_environment_name], but it doesn't work at the moment (see issue #130).
- it is unclear where to take this COILED_URI from. 

Proposed improvement:
- Docs could mention some of: "COILED URI is .....", "COULED_URI has the following format ....." ,"You can find COILED_URI in output from CLI ..., result of or in tab ... at cloud.coiled.io."

Most of this information is already available in docs of coiled.install(coiled_uri), so it should not be much trouble to output it in `coiled install --help`.

**Comment by FabioRosado** [comment]
Thank you again for your comments and feedback, I agree that we need to improve our documentation regarding the CLI options and we should rename this argument to something different.

Just to clarify `COILED_URI` is meant to be the software environment identifier (`<account>/<software env name>` or just `<software env name>` if the environment is in the same account.)

**Comment by FabioRosado** [comment]
Hello, this is now live on our latest coiled version (0.0.39.1), thank you so much for the feedback
