### ISSUE TITLE
Enhancement request: expose `private` option in CLI `coiled env create` 

### ISSUE THREAD

**Issue by jgawad-nlmk** [coiled/feedback#132]
Hi guys,

It would be helpful if `coiled env create` had feature parity with its `coiled.create_software_environment` counterpart. More specifically, it would be great to have `--private` option.

**Comment by FabioRosado** [comment]
Thank you for your suggestion. This seems like a good thing to implement - like you said, the CLI command should work similarly as the `coiled.create_software_environment`

**Comment by FabioRosado** [comment]
This is now available on our latest version of coiled - version 0.0.39.1 Thank you so much for the suggestion!
