### ISSUE TITLE
Support for setting a dask config in software environments

### ISSUE THREAD

**Issue by gjoseph92** [coiled/feedback#134]
A custom dask config is something more advanced users might want to control in their software environments. Though it's possible to bake one in using some [hacks in the post-build script](https://github.com/quasiben/dask-scheduler-performance/blob/769a0fa2332194388307b157b2f132c12efaa055/make-coiled-env.sh), a `dask_config=` parameter to software environments might be a reasonable convenience to offer? (This would just add the file and set the `DASK_CONFIG=` environment variable.)

The bigger issue is that software environments don't currently support adding custom files or environment variables (besides making your own Docker image). So a `files=` and `env=` argument could be a more general solution, and might be a prerequisite anyway for the `dask_config=` convenience.

**Comment by jrbourbeau** [comment]
xref https://github.com/coiled/feedback/issues/75

**Comment by gjoseph92** [comment]
Should have searched better! I'll close this duplicate.
