### ISSUE TITLE
Coiled blog post - outstanding TODO

### ISSUE THREAD

**Issue by hristog** [coiled/feedback#135]
Hi,

Unless it was intentional (e.g., intended as a joke/pun), I think there's an outstanding TODO in this [blog post](https://coiled.io/blog/data-science-deployments/):
> TODO: image of dask green check marks

Apologies if this was actually intentional.

**Comment by jrbourbeau** [comment]
That's definitely not intentional -- thanks for letting us know @hristog! 

cc @hugobowne @MichaMucha @mrocklin

**Comment by shughes-uk** [comment]
@scharlottej13 , this is still outstanding 😢

**Comment by scharlottej13** [comment]
Removed the TODO, thank you!
