### ISSUE TITLE
Provide feedback to user that a call to `destroy_cluster` worked correctly

### ISSUE THREAD

**Issue by ericdill** [coiled/feedback#14]
When I kill my clusters via `destroy_cluster`, it'd be nice to get some feedback that the cluster was, in fact, killed. Could be as simple as printing out f"cluster {name} successfully terminated".

```python
# kill all but 1 of the clusters
for idx, (cluster, metadata) in enumerate(clusters.items()):
    if idx == 0:
        continue
    cloud.destroy_cluster(metadata['typename'], metadata['name'])
```

**Comment by mrocklin** [comment]
Short term printing things out sounds like a great idea.  Long term I'm inclined to not call `print`.  Logging would be swell though.

Would your idea of including information in the Cloud repr suffice?  Presumably in the future we'll also have nice Bokeh plots or whatnot to help.

**Comment by ericdill** [comment]
To me, having info in the cloud repr is more of a discovery thing. At this point, I'd be inclined to recommend that (new) users _always_ show the cloud repr in their notebooks. That would have, at least for me, been a good trigger point of "oh crap I have a bunch of clusters running, that's weird".

Regarding confirmation that the cluster I tried to terminate actually terminated, that's a bit different, as it's explicitly user intent to get rid of those clusters. But I'm also skeptical of cloud resources behaving in general, so having confirmation that the cluster was killed means that I don't have to go check elsewhere (coiledhq.com, AWS ECS dashboard, etc.) that it was killed.

**Comment by ericdill** [comment]
(and yea, logging > printing :grin: )

**Comment by FabioRosado** [comment]
We have just merged some improvements to coiled. On version 0.0.37 upwards, we will show a message if the command `delete_cluster` is used - the same will happen to other commands that previously wouldn't give any feedback to the user.

I'm closing this issue since this will be available on the next coiled version. Please feel free to open a new issue if you encounter any issues or have any feedback 😄
