### ISSUE TITLE
Captcha on sandbox?

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#141]
I'm excited about the user-password login work happening.  However I currently don't seem to be able to engage past the captcha, which I'm not seeing.

![image](https://user-images.githubusercontent.com/306380/113901646-ac80ac80-9794-11eb-818c-e6cd5b7b421b.png)

**Comment by FabioRosado** [comment]
Looking at the console logs, it seems we are currently missing the recaptcha key

**Comment by ndanielsen** [comment]
Confirming that the recaptcha key wasn't included in the build. We'll have this back up on our sandbox for testing, etc pre-launch
