### ISSUE TITLE
Current Cost Per Hour (Coiled Credits) is not adjusted after scaling down the cluster

### ISSUE THREAD

**Issue by SultanOrazbayev** [coiled/feedback#157]
The cost per hour (at least as reported in the dashboard on the Coiled website) is not adjusted after cluster is scaled down. As far as I can tell, this only affects reported cost but not the billing.

Steps to reproduce:

1. Create a cluster:
```python
from coiled import Cluster
from distributed import Client

cluster = Cluster(n_workers=1)
client = Client(cluster)
```
2. On the `cloud.coiled.io` website the cost per hour will be reported as 8 credits per hour.
3. Scale the cluster up:
```python
cluster.scale(5)
```
4. On the `cloud.coiled.io` website the cost per hour will be reported as 24 credits per hour.
5. Scale the cluster down:
```python
cluster.scale(1)
```
6. On the `cloud.coiled.io` website the cost per hour will continue to be reported as 24 credits per hour.

**Comment by phobson** [comment]
Thanks for reporting this, @SultanOrazbayev. I'll make sure someone takes a look

**Comment by phobson** [comment]
@SultanOrazbayev -- @marcosmoyano fixed this a few days ago. I just scaled down a 100-worker cluster and the updated web UI responded impressively fast (to me at least)
![Screen Shot 2022-06-08 at 8 57 40 AM](https://user-images.githubusercontent.com/1163939/172663340-9a06c7c3-35ad-4249-ad78-f05aa80430b6.png)
