### ISSUE TITLE
Inalid token on sagemaker notebook instance

### ISSUE THREAD

**Issue by jorgesisco** [coiled/feedback#159]
**Description**
when I run the code:

`cluster = coiled.Cluster(name="demo-cluster", n_workers=5)
client = dask.distributed.Client(cluster)`

I get asked for my token, when I paste my token I get the an error:

`Invalid Coiled token encountered. Typically this occurs after logging out of 
https://cloud.coiled.io which resets your token for security reasons.`

I am login in coiled, so I don't get it.

**Additional context**
I am trying to reduce memory usage on dask dataframe to train my model on amazon sagemaker.

**Comment by marcosmoyano** [comment]
Hi Jorge, this usually means that you are using old style tokens.  You can create the new style tokens in your profile page (https://cloud.coiled.io/profile). Once that's stored in your coiled.yaml config file you should be good to go. Let us know if you need any more help.

**Comment by hayesgb** [comment]
Following up here @jorgesisco .  Did this fix your issue?

**Comment by jorgesisco** [comment]
Not yet, I think it might be Sagemaker not allowing to use coiled.

**Comment by jorgesisco** [comment]
I still get the error when I get asked for the token, even when I create a new one and add it right away.

**Comment by dchudz** [comment]
@jorgesisco Can you give a little more detail on what you're doing?

Specifically, how are you entering your token?

**Comment by shughes-uk** [comment]
Sagemaker token use seems to be fixed
