### ISSUE TITLE
Validators for AWS network names are wrong

### ISSUE THREAD

**Issue by jmathes** [coiled/feedback#161]
**Describe the bug**
In cloud.coiled.io/<account>/account/update-backend-options, after providing AWS credentials and asking to use an existing VPC and network resources, the input field validators assume each id is 17 characters long, which is not necessarily true

**Reference Links, optional**
There are slack threads in #general and #coiled-cloud

**Issue Priority, optional**
- [ ] Low
- [ ] Medium
- [ X ] High

**Environment, optional**
N/A; this is a bug with your website

**Diagnostics, optional**
N/A; this is a bug with your website

**Additional context**
the validators are regular expressions in src/pages/Account/UpdateOptions/AWS/index.tsx on line ~90:
            fieldValidations={{
              networkId: /^vpc-[A-Fa-f0-9/]{17}$/,
              schedulerSubnetId: /^subnet-[A-Fa-f0-9/]{17}$/,
              workerSubnetId: /^subnet-[A-Fa-f0-9/]{17}$/,
              firewallId: /^sg-[A-Fa-f0-9/]{17}$/,
              schedulerFirewallId: /^sg-[A-Fa-f0-9/]{17}$/,
            }}

**Comment by jmathes** [comment]
There are likely server-side validators that are also incorrect

**Comment by hayesgb** [comment]
cc: @dchudz

**Comment by dchudz** [comment]
Joe: Sorry about this, and thanks for pointing it out. 

Internal issue: https://gitlab.com/coiled/cloud/-/issues/4943

**Comment by jmathes** [comment]
Thanks. This is preventing us from productionizing a system that pays you money :)

**Comment by 0-ren** [comment]
Hey @jmathes 

While we're working on fixing this, I'd love to talk more about your use case, get you some more special attention, and figure out how we can make your life easier. And get that productionizing popping asap. 

Are you free sometime this week to talk? [Here's a link to my calendar](https://calendly.com/d/dtn-w6c-tr9/talk-about-coiled-o_p?month=2022-06) where you can find a time that works best for you. 

Thanks!

**Comment by jmathes** [comment]
Is there any chance I could get an ETA on this? It's a blocker and it'll affect our internal planning

**Comment by dchudz** [comment]
@jmathes I also wanted to mention `coiled.set_backend_options` which you could use as an alternative to the UI. (Some of our users prefer configuring things with code, and this should also sidestep the validation since we aren't checking lengths server-side.)

**Comment by jmathes** [comment]
Thanks so much!
