### ISSUE TITLE
Upgrade Account UI fails

### ISSUE THREAD

**Issue by phobson** [coiled/feedback#165]
_from https://coiled.zendesk.com/agent/tickets/88 (May 13)_

A Zendesk user writes:
> I want to upgrade my account to a pro account to get immediate access, but after entering my credit card information it spins for a while and it says "unknown error occurred". I'm assuming it is because my "opt in" activation request has not been granted yet. I am trying to use coiled as a solution to get some compute going fast with dask (we already have a dask set-up)

**Comment by shughes-uk** [comment]
issue is too stale for us to find traces or logs related to it, not sure we can do anything
