### ISSUE TITLE
"cost per operation" maybe should be "time per operation"?

### ISSUE THREAD

**Issue by rsignell-usgs** [coiled/feedback#176]
In the cluster analytics plots (which are very cool!) I found the title of "cost per operation" confusing because I was expecting $ when I saw cost, but the y axis units are "compute time (hr)".

**Comment by mrocklin** [comment]
@FabioRosado probably?

**Comment by FabioRosado** [comment]
Yeah happy to take this on when I'm back on Monday 😀

**Comment by FabioRosado** [comment]
Hello, we deployed a fix for this yesterday. Closing this issue now but feel free to reopen
