### ISSUE TITLE
Mention cluster name in "STOP CLUSTER?" modal

### ISSUE THREAD

**Issue by hendrikmakait** [coiled/feedback#180]
**Description**
As a user with multiple running clusters, I would like to see the name of the cluster I selected to stop mentioned in the modal to make sure that I am dealing with the correct one.

**Is your feature request related to a problem? Please describe.**
With multiple running clusters and new ones occasionally spinning up, I am sometimes uncertain whether I selected the correct cluster to stop or whether the site refreshed just before, moving another one under my cursor.

**Comment by FabioRosado** [comment]
This was implemented and merged in, when we deploy you will be able to see the cluster name when trying to stop a cluster. Thank you @hendrikmakait  for the suggestion!
