### ISSUE TITLE
Cluster details page is missing a link to the dashboard

### ISSUE THREAD

**Issue by fjetter** [coiled/feedback#190]
The cluster details page is missing a link to the dashboard. 

![image](https://user-images.githubusercontent.com/8629629/185949725-6cc30250-0256-4c92-afa8-a41bd990ecd6.png)

The only way to get that link right now is to navigate back to the cluster overview page where there are potentially *many* clusters and it is difficult to find the correct link

**Comment by shughes-uk** [comment]
The link is the breadcrumb, we should think about making it more obvious as it's kinda hidden
<img width="1722" alt="Screen Shot 2022-08-22 at 12 38 47 PM" src="https://user-images.githubusercontent.com/546891/186004698-58ebb048-bd0f-477b-bebe-d6ddf4bb503a.png">

**Comment by shughes-uk** [comment]
Resolved
