### ISSUE TITLE
Collaboration with Prefect and Coiled

### ISSUE THREAD

**Issue by scharlottej13** [coiled/feedback#191]
**Description**

Our most popular how-to guide in the Coiled docs is [our guide on using Coiled with Prefect](https://docs.coiled.io/user_guide/examples/prefect.html). We'd love to collaborate with the folks at Prefect to make sure using Prefect 2.0 and Coiled is smooth and enjoyable.

This issue is to scope out what that collaboration might look like. Ideas include a video tutorial ([Kevin Kho's video](https://www.youtube.com/watch?v=awXYHAkY2To) from the 2021 Dask Summit is great), a blog post, an updated how-to guide, etc.

Thanks @anna-geller for being open to discussing this more with us! Looking forward to hearing your (and others') thoughts. @dchudz @jrbourbeau feel free to chime in or suggest others who might want to.

**Comment by khuyentran1401** [comment]
Hi @scharlottej13, great idea! I'm a developer advocate at Prefect and would love to collaborate with you on this. I was thinking about a blog post and a video tutorial. How would you like to collaborate together?

**Comment by scharlottej13** [comment]
Hi @khuyentran1401, nice to meet you! I think a blog post and video tutorial would be great. Did you already have ideas around specific content we should focus on? Here are some suggestions:
- syntax changes from executors to task runners mentioned in [Prefect's migration guide](https://docs.prefect.io/migration-guide/#conceptual-and-syntax-changes)
- new features particularly relevant to Dask or Coiled (needs some brainstorming on my part, but `subflows` seems like potentially a good one)
- address common pain points people have w/ Prefect + Coiled (another item for brainstorming)

**Comment by khuyentran1401** [comment]
Hi @scharlottej13, thanks for the suggestion. What do you think if we collaborate on an article that shows an application on how to use Prefect 2.0 with Coiled like [this one](https://docs.coiled.io/user_guide/examples/prefect.html)? We could discuss how to do exactly that through a short call. What do you think?

**Comment by scharlottej13** [comment]
@khuyentran1401 that sounds great! I just slacked you on the Prefect slack so we can find a good time. Thanks!

**Comment by shughes-uk** [comment]
Any update @scharlottej13 ?

**Comment by scharlottej13** [comment]
Thanks @shughes-uk! We made some progress here (full conversation in referenced issue) but we still have some work to do before picking this up again. I'll close this issue for now, we discuss future collaborations in a separate issue as they come up.
