### ISSUE TITLE
WARNING:root:Error getting STS token from client AWS session: Could not connect to the endpoint URL

### ISSUE THREAD

**Issue by tonycombocurve** [coiled/feedback#199]
We see this warning every time we connect to a coiled cluster:

`
WARNING:root:Error getting STS token from client AWS session: Could not connect to the endpoint URL: "http://169.254.169.254/latest/api/token"
`

We are running on Google Cloud so it's very confusing to the developer to see this warning.

**Issue Priority, optional**
- [x] Medium

**Environment, optional**
- Python version: 3.9.13
- coiled-runtime version: 0.2.27

**Comment by tonycombocurve** [comment]
Duplicate of https://github.com/coiled/feedback/issues/195

**Comment by ntabris** [comment]
closing in favor of #195 (but let me know if there's a reason for this new issue)
