### ISSUE TITLE
Scary looking warning with no STS tokens

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#202]
```
WARNING:root:Error getting STS token from client AWS session: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
```

I don't have AWS credentials set up locally.  That's ok I think, but I get this scary looking warning when I make a cluster.  Maybe it should be gentler.

**Comment by ntabris** [comment]
Yep, already reported https://github.com/coiled/feedback/issues/195, fix will go out with next release.

**Comment by mrocklin** [comment]
Oh grand.  I love how quickly things get fixed around here 😉
