### ISSUE TITLE
Cluster dashboard page very CPU hungry

### ISSUE THREAD

**Issue by fjetter** [coiled/feedback#205]
The cluster dashboard page can be very CPU intensive. For the dask-engineering user where we have a couple hundred clusters and there is typically always something active this occasionally uses up all CPUs on my M1 (I'm using Chrome)

**Comment by ntabris** [comment]
Just to be explicit, when you say "cluster dashboard" you mean the page with this?

<img width="977" alt="image" src="https://user-images.githubusercontent.com/46289310/190637751-13aae3b4-fb14-472a-aa59-54d4f94ab502.png">

**Comment by fjetter** [comment]
> Just to be explicit, when you say "cluster dashboard" you mean the page with this?

yes

**Comment by FabioRosado** [comment]
we can probably return less items. It's in my queue to work on this page and make the table better but I have some things to do first like updating our material ui library before I take on changing this page

**Comment by shughes-uk** [comment]
Pagination is the solve here, @FabioRosado's work with updating MUI should let us use a nicer component and paginate things properly

**Comment by ncclementi** [comment]
> we can probably return less items
I'm trying to check on a cluster in the dashboard page, and it's pretty unresponsive, can't filter or check details pages, it's like frozen, Can we display fewer clusters until we have pagination?

**Comment by dchudz** [comment]
@ncclementi if we're just talking about temporary workarounds for now... do you actually need the dashboard page?

if you have the cluster ID, you can go right to the details page (the coiled client gives you a link when the cluster starts up).

Does that get you what you're trying to check on?

**Comment by FabioRosado** [comment]
I'll do the quick fix Monday (we still would need to deploy) for now David's suggestion is a good idea

**Comment by ncclementi** [comment]
> Does that get you what you're trying to check on?
I was trying to find an older (from yesterday) cluster, that I did not have the details page link because the notebook output was cleared out. I wanted to check some versions of packages installed but there was no way to find the cluster. This is not critical, so I can live with it.

**Comment by dchudz** [comment]
I see, thanks Naty. And thanks Fabio!

**Comment by fjetter** [comment]
> if we're just talking about temporary workarounds for now... do you actually need the dashboard page?
> 
> if you have the cluster ID, you can go right to the details page (the coiled client gives you a link when the cluster starts up).

I consider the dashboard page pretty important. I often don't have the cluster ID at hand and need this page to navigate and find clusters that just started.
I also think a filter is required but that's obviously a different topic

**Comment by shughes-uk** [comment]
Dashboard is paginated now and is way less intensive
