### ISSUE TITLE
account deletion

### ISSUE THREAD

**Issue by gabrielliu** [coiled/feedback#208]
Hi,

I would like to request to delete my account

Thanks

**Comment by phobson** [comment]
@gabrielliu -- thanks for dropping us a note. We'll let you know when it's done.

**Comment by phobson** [comment]
@gabrielliu under what email address did you sign up for Coiled? Or did you use Github SSO?

**Comment by phobson** [comment]
@gabrielliu Could you provide more information about how you signed up (email address, Gmail or Github SSO, etc)?

**Comment by gabrielliu** [comment]
email address: liuz@mail.sacredheart.edu

Thank you.

**Comment by FabioRosado** [comment]
Hello, 

apologies for the delay, this is now done
