### ISSUE TITLE
Cluster repr printed twice in jupyter

### ISSUE THREAD

**Issue by fjetter** [coiled/feedback#214]
The HTML repr seems to be shown twice in jupyter when just "printing" the cluster object

![image](https://user-images.githubusercontent.com/8629629/201114045-a3a2ac2a-b56a-48db-b5e1-c0708ea196e1.png)

coiled version `0.2.41`

**Comment by pont-us** [comment]
I'm seeing the same behaviour with Coiled 0.2.59.

Attached: [package-list.txt](https://github.com/coiled/feedback/files/10455101/package-list.txt), full package list for my JupyterLab environment in case it's relevant for debugging.

**Comment by shughes-uk** [comment]
Is this still happening? There was an issue with `rich` which I believe is now resolved

**Comment by fjetter** [comment]
haven't seen it in a while. I'll reopen if I encounter it again
