### ISSUE TITLE
Coiled Docs - Configuring AWS - IAM Policy Issue

### ISSUE THREAD

**Issue by IndexSeek** [coiled/feedback#219]
While configuring the AWS backend for Coiled following the docs and creating the [corresponding IAM policies/creating user](https://docs.coiled.io/user_guide/aws_configure.html#create-iam-policies) using the Browser Setup in the Preferred Flow, I encountered the following error:

`Error configuring backend: An error occurred (AccessDeniedException) when calling the CreateLogGroup operation: User with accountId: [0-9] is not authorized to perform CreateLogGroup with Tags
Error encountered configuring network, trying to clean up`

I was able to resolve this error by adjusting the `cloud-ongoing` IAM policy and adding the `"logs:TagLogGroup"` permission. I was glad this could be resolved but hoping to make it easier for future users on setup, and want to ensure I'm resolving correctly on my end. 

**Issue Priority**
- [ ] Low

**Comment by ntabris** [comment]
Thanks, we'll update those docs!

**Comment by ntabris** [comment]
docs and cli setup have both been updated to include this permission

**Comment by ntabris** [comment]
@IndexSeek thanks again for bringing this to our attention!
