### ISSUE TITLE
AWS S3 Not work with dask

### ISSUE THREAD

**Issue by b-y-f** [coiled/feedback#220]
**Description**
The task is to read a list(length about 40k) of s3 paths and do an ML job(random forest classification) on those data from the s3 path, then write prediction results by different names to s3. To implement the method, I was referring to [this page](https://examples.dask.org/applications/embarrassingly-parallel.html).
the data flow is like

```
d1                                 output1
d2                                 output2
d3                                 output3
d4   --> [function(s3_path)] -->   output4
d5                                 output5
dn                                 output_n
```

And I was using 

```python3
import dask
import awswrangler
lazy_results = []

def my_func():
        df=awswrangler.read_parquet(s3)
        result = do_something_with_df(df)
        # upload to s3 the result
        awswrangler.write_parquet(result,s3)

for parameters in input_params.values:
    lazy_result = dask.delayed(my_func)(parameters)
    lazy_results.append(lazy_result)

futures = dask.persist(*lazy_results)  # trigger computation in the background
# or futures = dask.compute(*lazy_results)
```

The computation is not in cluster when I watch the dashboard.

**Is your feature request related to a problem? Please describe.**

**Additional context**
AWSCLI credential got full access.

Im using all default setting, with env :
```
conda:
{
  "channels": [
    "conda-forge"
  ],
  "dependencies": [
    "coiled-runtime",
    "dask",
    "pandas",
    "scikit-learn"
  ]
}
pip:
[
  "awswrangler"
]
```

**Comment by mrocklin** [comment]
Hi @b-y-f , from what you've written I don't see anything wrong.  You might have to provide some more context.

What happens?  Do you get any errors?  In what state are the futures?  Are they still pending?  Finished?  Erred?

How are you setting up your Dask cluster?  Are you making a Client and giving it that cluster?

**Comment by b-y-f** [comment]
I don't know the reason. From the cluster dashboard I can't find any thing is running. And the default aggregation of sample data works and I can see something is running from dashboard. But from my above code ,I can't find anything is moving.

**Comment by b-y-f** [comment]
> Hi @b-y-f , from what you've written I don't see anything wrong.  You might have to provide some more context.
> 
> 
> 
> What happens?  Do you get any errors?  In what state are the futures?  Are they still pending?  Finished?  Erred?
> 
> 
> 
> How are you setting up your Dask cluster?  Are you making a Client and giving it that cluster?

Maybe I will find a time to paste a reproducible code.

**Comment by mrocklin** [comment]
> Maybe I will find a time to paste a reproducible code

That would be useful.  From what you have written so far we're unable to diagnose the issue.

**Comment by b-y-f** [comment]
Worked thanks
