### ISSUE TITLE
Duplicated stale metadata causing package sync to install incorrect versions

### ISSUE THREAD

**Issue by fjetter** [coiled/feedback#223]
I can see AWS import errors in my worker logs

https://cloud.coiled.io/dask-engineering/clusters/128646/details

```
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]: Traceback (most recent call last):
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]:   File "https://cloud.coiled.io/api/v2/cluster_facing/preload/aws-creds-loader", line 20, in setup
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]:   File "/opt/coiled/env/lib/python3.10/site-packages/s3fs/__init__.py", line 1, in <module>
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]:     from .core import S3FileSystem, S3File
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]:   File "/opt/coiled/env/lib/python3.10/site-packages/s3fs/core.py", line 14, in <module>
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]:     from fsspec.utils import infer_storage_options, tokenize, setup_logging as setup_logger
Dec 14 10:39:11 ip-10-0-0-168 cloud-init[845]: ImportError: cannot import name 'setup_logging' from 'fsspec.utils' (/opt/coiled/env/lib/python3.10/site-packages/fsspec/utils.py)

```

Tested on `coiled==0.2.43` and `coiled==0.2.55`, both with `fsspec==2022.7.1 `

**Comment by dchudz** [comment]
@fjetter according to https://cloud.coiled.io/dask-engineering/clusters/128646/software/2443?tab=installed, your version of fsspec on the cluster is 0.2.3 and locally is 0.2.0.

Is that not right?

Is `fsspec==2022.7.1` definitely is what you have locally?

If so we have some weird package sync bug to work out, I think.

**Comment by dchudz** [comment]
(Tagging @shughes-uk since you may be interested but nothing needed from you right now until I hear back from Florian...)

**Comment by fjetter** [comment]
![image](https://user-images.githubusercontent.com/8629629/207599959-8e1ed70d-2079-4624-9a1d-64ef212dea8f.png)

**Comment by fjetter** [comment]
Yes, package sync logs state that they are uninstalling my 2022.7.1 version in favor of the old 0.2.3 version... and they are building a wheel for it. that's very strange...

**Comment by dchudz** [comment]
@shughes-uk you want to take a look ... ?

**Comment by fjetter** [comment]
I _think_ I targeted the same env as yesterday but am not 100% sure...

[package_sync_debug.txt](https://github.com/coiled/feedback/files/10239554/package_sync_debug.txt)
[package_sync_scan.txt](https://github.com/coiled/feedback/files/10239555/package_sync_scan.txt)

**Comment by shughes-uk** [comment]
Looks like your environment is slightly out of whack. You have two `.dist-info` folders for `ffspec`
```
│ /Users/fjetter/mambaforge/envs/dask-distributed-310/lib/python3.10/site-packages/fsspec                                            │
│ /Users/fjetter/mambaforge/envs/dask-distributed-310/lib/python3.10/site-packages/fsspec-0.2.0.dist-info                            │
│ /Users/fjetter/mambaforge/envs/dask-distributed-310/lib/python3.10/site-packages/fsspec-2022.7.1.dist-info                         ```
Cleaning up the 0.2.0 one will result in a happy situation. 

Not 100% sure how to deal with this, possibly I could check the file creation dates and use the latest one when this happens? 

Seems to occur sometimes when killing `pip` or such, it fails to clean up a package.

**Comment by dchudz** [comment]
@shughes-uk -- Florian's local python is picking up one of them somehow. Do we know what determines which? Presumably the goal is to do whatever his local Python would do...? (But maybe that's hard.)

**Comment by shughes-uk** [comment]
So the source files are in the `fsspec` directory, `pip list` i suspect will report verison in the the last `.dist-info` metadata folder it sees. But really you have no way of knowing what is installed without taking a guess based on timestamps (or looking at a provided __version__.py is there is one). 

It's a "corrupt" environment. Quotes on corrupt because this does not matter apart from our specific use case

**Comment by dchudz** [comment]
I see... I was hoping we can pick whichever one `import fsspec` gets, but... `import fsspec` doesn't use the metadata and we do?

**Comment by shughes-uk** [comment]
Correct. It ignores that. Checking timestamps on the metadata and grabbing the latest one is probably best effort

**Comment by fjetter** [comment]
Thanks for digging in. I noticed with the same environment an issue where vscode would claim the environment was not a proper conda environment and it refused to perform certain operations. I never found out what it was and in the past I recreated my environment. I ran into this issue a couple of times now...

Might be worth raising during cluster creation if we detect such a condition

**Comment by shughes-uk** [comment]
Package sync should now be properly using the version of the package you get when you `import foo`
