### ISSUE TITLE
Update RAPIDS container image to 22.12 in GPU docs

### ISSUE THREAD

**Issue by jacobtomlinson** [coiled/feedback#224]
Hey folks! RAPIDS `22.12` has been released. Could https://docs.coiled.io/user_guide/gpu.html be updated to use the new Docker image.

I've tested the instructions up to the verification section and all seems good with `22.12`.

cc @ntabris @dchudz @scharlottej13

**Comment by scharlottej13** [comment]
Thank you @jacobtomlinson! Just opened an MR with the change for internal review.

**Comment by scharlottej13** [comment]
Closing since this update has been released. Thanks!
