### ISSUE TITLE
I got error: MaxFleetCountExceeded

### ISSUE THREAD

**Issue by kidesigner** [coiled/feedback#225]
I use S3 provider, Free tier, and I got error:
 Cluster status is error (reason: Scheduler Stopped -> Instance failed: MaxFleetCountExceeded -  │
│ You've reached your quota for maximum Fleet Requests for this account.)

Can you help me?

**Comment by ntabris** [comment]
Hi @kidesigner. On an earlier cluster from today I saw you got this error back from AWS:

```
Blocked - This account is currently blocked and not recognized as a valid account. Please contact aws-verification@amazon.com if you have questions.
```

Is your AWS account otherwise working for you? I'm wondering if the `MaxFleetCountExceeded` error is misleading and there's another problem with your account, as indicated by the "blocked" error.

**Comment by kidesigner** [comment]
Thank for fast support. It's AWS issues, I contacted to Amazon Support. Again, Thank you
