### ISSUE TITLE
Update RAPIDS release to 23.02

### ISSUE THREAD

**Issue by jacobtomlinson** [coiled/feedback#230]
Hey folks, it's that time of the "bi-month? 🤔". 

RAPIDS `23.02` is out and I've just tested Coiled's GPU instructions with it and everything looks good.

Could someone bump the container image on this page https://docs.coiled.io/user_guide/gpu.html

Needs to be `rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu20.04-py3.10`. (Note that the Python version needs bumping too).

Thanks!

**Comment by ntabris** [comment]
thanks for the reminder, it will be updated in the next release (probably today).

I was planning to use `rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu22.04-py3.10` (unless ubuntu22 is a bad choice?)

**Comment by jacobtomlinson** [comment]
Thanks! Sure go for it, we haven't updated our deployment docs to use 22.04 by default yet, but we will soon. I don't expect there to be any problems.

**Comment by shughes-uk** [comment]
Done
