### ISSUE TITLE
Unable to login to free trial account 

### ISSUE THREAD

**Issue by marcdhansen** [coiled/feedback#231]
**Unable to login to free trial account**
When I try to login by clicking the link to my Google account, I get an error saying there’s already a user with that email and I should try to login again

**Additional context**
Snapshot of error message:
![7A5E1E5C-2767-4412-BC8A-8B91C9A86DF0](https://user-images.githubusercontent.com/7607160/221667135-d71f7ec1-4a99-4479-a815-459e97bbafcc.jpeg)

**Comment by shughes-uk** [comment]
Hiya, we're working on a fix for this and hoping to have something deployed by EOD. I'll let you know when we have it out

**Comment by marcdhansen** [comment]
I’m now able to login.  Thanks for the quick fix!
