### ISSUE TITLE
Accessing remote data on workers via a mounted file share

### ISSUE THREAD

**Issue by lfraker** [coiled/feedback#232]
**Description**

We're running Coiled on AWS. We have an Azure Files-based file share with data our cluster jobs need to access. For the most performant read/write, we'd like to mount the file share (SMB protocol). From what I can tell this doesn't appear to be possible with the default setup (our code is only executing in a running container with limited permissions).

It seems like one approach would be to build a custom Docker image (https://docs.coiled.io/user_guide/docker.html) with our file share as a mounted Volume, then base our cluster containers on this image (we're using the AWS ECR option at setup time).

Before testing this approach, I wanted to check if there was any other recommended way to mount a file share over SMB and grant access to the Dask cluster workers?

**Comment by ntabris** [comment]
Hi, @lfraker. The short answer is that we do not currently have a recommended way to mount a file share on a Coiled cluster. Mostly people use blob storage (such as S3) via `fsspec`.

I'd be interested in learning more about your use-case (if you don't mind sharing). Are you currently using SMB with many workers having concurrent access? Is this read/write/both? Is the main reason you want file share because that's where you already have data, or are there other reasons that blog storage wouldn't work well for your use-case?

**Comment by lfraker** [comment]
Hi @ntabris thanks for the clarity! without going into too much detail, it's a combination of reasons - there will be concurrent access across many workers, but at the moment, that data needs to also be easily and efficiently programmatically/manually accessible on local machines, and a mounted file share was the best option. Unfortunately, we can't use something like BlobFuse due to lack of OS support.

If I were to try the mounted Volume approach on the docker image, do you see any reason why it wouldn't work from the Coiled side (I'm guessing no, cause it seems like you'd just swap that image in as the Dask environment)?


Also sorry to add an unrelated question (let me know if you need me to raise a separate issue), but I'm running into a bit of trouble with IP allow-listing when making an outbound call from the Coiled Dask workers. It doesn't look like the default Coiled AWS setup deploys any kind of NAT Gateway/Static IP for outbound traffic (please let me know me if I'm wrong). If we want outbound traffic from the Dask workers to originate from a Static IP, is the correct approach to add this configuration after the initial Coiled VPC setup?

If we make updates, is there any risk of Coiled ever updating the VPC resources and overwriting our additional config (it doesn't look Coiled deployed via any kind of CloudFormation Stack, so I'm hoping auto-updates, if ever done, wouldn't impact post-setup config)?

**Comment by ntabris** [comment]
> If I were to try the mounted Volume approach on the docker image, do you see any reason why it wouldn't work from the Coiled side (I'm guessing no, cause it seems like you'd just swap that image in as the Dask environment)?

I haven't tried. If you're up for trying, I'd be happy to help (get on a call or whatever) if you run into problems.

> It doesn't look like the default Coiled AWS setup deploys any kind of NAT Gateway/Static IP for outbound traffic (please let me know me if I'm wrong). If we want outbound traffic from the Dask workers to originate from a Static IP, is the correct approach to add this configuration after the initial Coiled VPC setup?

It sounds like you want to setup a NAT Gateway and route through that, and it sounds like you probably understand how to do that part.

Coiled has the default "we setup and manage the networking for you" mode, and the "you do what you want with the network" mode. To manage the networking yourself, you'd do account setup via the "browser" flow as explained in [this doc](https://docs.coiled.io/user_guide/aws_configure.html#configure-your-coiled-cloud-account), and say you want to use and existing VPC. (This could be the VPC that Coiled already created in your account, or could be another that you create.) You'll then tell us the ARNs for various network resources to use:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/46289310/225740248-0ca86b29-03e2-4bf5-b2ee-ad4c2570a280.png">

You probably want to do something like the example in [this doc](https://docs.coiled.io/user_guide/tutorials/bring_your_own_network.html#aws-example-public-and-private-subnets).

Let me know if you have questions about any of that.

**Comment by lfraker** [comment]
Regarding the mounted Volume, I'll update this thread if we try it/if it works!

For the networking, I didn't consider re-using the Coiled-provisioned Networking resource, but that's a great point. The linked doc definitely looks like what we want, I'll give that setup a try!

@ntabris I'm happy to close this issue for now since all my open questions are answered. Thanks again!

**Comment by ntabris** [comment]
> I didn't consider re-using the Coiled-provisioned Networking resource, but that's a great point

Just to be clear, we create VPC and public subnet. You'll need to create the private subnet you want, as well as the security groups.

**Comment by lfraker** [comment]
@ntabris thanks for clarifying. To make sure I'm understanding, if I already went through the Coiled 'default' network setup flow, can I create the gateway and private subnet resources via AWS CLI/Console under that existing VPC, or do I need to delete the 'default' resources and run through the setup in Coiled again with the 'bring your own network' flow?

I guess I'm asking if Coiled will ever execute any creation/deletion/update commands on the networking resources after the initial 'default' setup flow (commands that could break any subnets/gateways I added manually)? Or, does Coiled never touch the networking resources after the initial setup under the 'default' flow?

**Comment by ntabris** [comment]
> can I create the gateway and private subnet resources via AWS CLI/Console under that existing VPC

Yes, that should be fine

**Comment by lfraker** [comment]
@ntabris I ran into a few other issues/questions following the NAT gateway approach - raised a separate issue to keep this thread clean https://github.com/coiled/feedback/issues/233#issue-1634649155, but I would appreciate any thoughts if you're able to take a look

**Comment by KristofferFogh04** [comment]
Hi @lfraker 
It's been a while, but I'll try asking anyways. I am currently having the same issue as you, trying to access data from an Azure fileshare inside the cluster jobs. Did you manage to solve your problem, or did you find a workaround?

**Comment by ntabris** [comment]
Hi, @KristofferFogh04. I'll email you about this.

**Comment by lfraker** [comment]
@KristofferFogh04, @ntabris will definitely be more helpful than I can be with this. Good luck!

**Comment by KristofferFogh04** [comment]
Thanks for the swift reply both of you!

@ntabris Alright, sounds good. I'm awaiting this. It should be mentioned also that I'm using Coiled on Azure so I'm aware that it's in beta and some features might be missing. But just wondering whether anyone has ever connected fileshares to the VM's spawned by the Azure Virtual Machine Scale Sets.

**Comment by ntabris** [comment]
Hi @KristofferFogh04. Did you get the email from me yesterday? If not, could you please email support@coiled.io and I'll reply to your email.
