### ISSUE TITLE
Sending private environment variables via  `coiled run` command

### ISSUE THREAD

**Issue by andersy005** [coiled/feedback#260]
Per [documentation](https://docs.coiled.io/user_guide/remote-data-access.html), one can send private environment variables via the `.send_private_envs()` method. 

```python
cluster = coiled.Cluster(...)
cluster.send_private_envs({"AUTH_TOKEN_FOR_CUSTOM_DATABASE": "some-token"})
```

now, i'm wondering if there is a way to use this option with the `coiled run ....` command. specifically,  i'd like to specify the `AUTH_TOKEN_FOR_CUSTOM_DATABASE` when invoking `coiled run ....`.

for instance, currently, my command looks like this:

```bash
coiled run --container quay.io/ORG/CONTAINER  bash main.sh 
```

i'm curious to know if there are any other better alternatives available at the moment.

**Comment by jrbourbeau** [comment]
@andersy005 `--env FOO=bar` was just included on our end. We release most days, so the new option will most likely be out by tomorrow (I'll ping this issue when things are out)

**Comment by dchudz** [comment]
@andersy005 you can try it now with `pip install coiled==0.9.38.dev13`
