### ISSUE TITLE
coiled setup gcp results in FileNotFoundError 

### ISSUE THREAD

**Issue by adrianbeer** [coiled/feedback#262]
Using Windows with Python version 3.10.13. gcloud is installed and works in the command line, however `coiled setup gcp` gives me the following error.
It appears to me that `subprocess` doesn't have access to PATH as `shell=False` per default, so it can't locate the `gcloud` command.

![image](https://github.com/coiled/feedback/assets/36116108/ddf14744-129f-4a75-b5e5-9b7c67c8f514)

**Comment by dchudz** [comment]
Hi Adrian-- sorry about this! We should be able to get that fixed in the next day or two.

**Comment by dchudz** [comment]
Should have a fix for you tomorrow, Adrian.

**Comment by dan-blanchard** [comment]
@adrianbeer, we deployed a fix, so please let us know if you still encounter this issue after upgrading the coiled client.

**Comment by adrianbeer** [comment]
Can confirm that it works now, thanks!
