### ISSUE TITLE
Coiled Dashboard link not accessible on a CI system

### ISSUE THREAD

**Issue by aimran-adroll** [coiled/feedback#264]
In the CI system, the generated dashboard link does not have the appropriate auth to click through. 

e.g If we do the recommended 

```python
from coiled import Cluster
cluster = Cluster(...)

from dask.distributed import Client
client = Client(cluster)
print('Dashboard:', client.dashboard_link)
```

it spits out a link just fine with `...?token=dOneHeSE8RAR5ic1` bit as well. But clicking on the link takes me to this page

![image](https://github.com/coiled/feedback/assets/31903245/dd7b389c-f6d9-44d6-89a7-72a84d3dfb39)

I also noticed the "dashboard link" from the coiled page is not accessible in this case as well. It brings up the same error page as above ☝🏽 

![image](https://github.com/coiled/feedback/assets/31903245/f235fda4-6390-4879-b083-b28b1a7f30e8)

**Comment by phofl** [comment]
Hi,

sorry for the confusing error message here. This error also shows up if you don't have bokeh installed in your environment. Your latest cluster doesn't seem to have it installed, so adding bokeh should fix that (the Dashboards are built with bokeh)

**Comment by aimran-adroll** [comment]
Ah! Thanks Patrick. Will try it and report back

**Comment by aimran-adroll** [comment]
@phofl sorry, completely forgot to close out the issue. Your diagnosis was spot on. Thanks
