### ISSUE TITLE
struggling with parallel particle tracking simulations with Coiled

### ISSUE THREAD

**Issue by rsignell** [coiled/feedback#269]
I was excited to read https://medium.com/coiled-hq/processing-terabyte-scale-nasa-cloud-datasets-with-coiled-70ab552f35ec blog post by @jrbourbeau because I have basically the same use case: running a bunch of particle tracking simulations that are completely independent: a tracking function with a single argument (start_time), called with a list of different start times.  

I used the code in the blog post as a template and created [this reproducible notebook](https://gist.github.com/rsignell/dbf9776c11fe8d4b03d77693cd29dd23) (reads from object storage with no credentials needed!)

**Running Locally**, I successfully ran simulations in parallel using a local client with Dask futures.

**Running with Coiled**, the code didn't run.    I used a Coiled environment that matched my local conda environment (using the same conda environment file) but [the code seems to have died](https://cloud.coiled.io/clusters/366655/information?account=open-science-computing&computation=14ca47b8-bf96-438e-9b24-906e56e8e0af&sinceMs=1706462959782&untilMs=1706463204333) in a Scipy `LinearNDInterpolator` routine?

I'm a bit lost here on what is wrong -- hoping someone the Coiled team can help me out!

**Comment by phofl** [comment]
Hi,

the worker is paused because memory usage is high, could you maybe try this again with bigger machines to see if this fixes the problem?

The relevant section of the logs:

```
2024-01-28 17:30:23.4080
scheduler
distributed.worker.memory - WARNING - Worker is at 82% memory usage. Pausing worker.  Process memory: 4.68 GiB -- Worker memory limit: 5.70 GiB
2024-01-28 17:30:23.3160
scheduler
distributed.worker.memory - WARNING - Worker is at 78% memory usage. Resuming worker. Process memory: 4.47 GiB -- Worker memory limit: 5.70 GiB
2024-01-28 17:30:23.0770
scheduler
distributed.worker.memory - WARNING - Worker is at 80% memory usage. Pausing worker.  Process memory: 4.56 GiB -- Worker memory limit: 5.70 GiB
```

**Comment by rsignell** [comment]
Thanks for looking into this @phofl !
I thought the above was okay because they were WARNINGs.   When I previously successfully ran a single process using Coiled it used about 5GB RAM so I thought I would be okay. 

But I ran again specifying at least 8GB RAM 
https://cloud.coiled.io/clusters/367372/information?account=open-science-computing
and those warnings went away but now the simulations got stuck again with:
```
2024-01-29 07:17:35.8670
10.0.57.202

Dask stopped
Dask process stopped
2024-01-29 07:17:35.8320
10.0.57.202

VM Instance stopped
Dask graceful shutdown
2024-01-29 07:17:04.4520
10.0.57.202

VM Instance stopping
Software environment exited
2024-01-29 07:17:02.8800
10.0.57.202

Dask stopping
Dask process exiting
2024-01-29 07:15:24.1450
10.0.57.202

distributed.worker - WARNING - Compute Failed
Key:       process-24acb7c2-1d4d-4060-9989-174258d03558-1
Function:  process
args:      (datetime.datetime(2012, 1, 29, 0, 0))
kwargs:    {}
2024-01-29 07:15:05.1020
scheduler

distributed.core - INFO - Event loop was unresponsive in Scheduler for 4.02s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-29 07:15:01.0000
scheduler

distributed.core - INFO - Starting established connection to tls://10.0.62.156:56726
2024-01-29 07:15:00.9990
```

**Comment by fjetter** [comment]
I'm not sure why your cluster appeared to be stuck but I can see dying workers due to an unhandled exception in deserialization. This goes back to fsspec and I opened an upstream issue https://github.com/fsspec/filesystem_spec/issues/1520

It looks like you did receive a "compute failed" error log. Did you not receive an exception on client side?

**Comment by rsignell** [comment]
This is all I see on the client side: https://nbviewer.org/gist/rsignell-usgs/b925c9968fe2db09c0413a080de3e99a

**Comment by jrbourbeau** [comment]
Hey @rsignell -- glad to hear you found the post useful. Sorry things aren't working out of the box for your application. 

Sort of a side comment, but right now the `process` function is saving a new output file to each time it's run and the available disk on the VMs will eventually fill up

![Screenshot 2024-01-29 at 10 14 40 AM](https://github.com/coiled/feedback/assets/11656932/2dd9eb61-b739-4f61-91b0-c8577fce0d94)

If you write the output file to the temporary directory in the snippet with

```python
ncfile = f'{tmpdir}/opendrift_{start_time.strftime("%Y%m%d")}.nc'
```

the output files will be cleaned up after each `process` function call

Is the Xarray dataset returned by `process` backed by NumPy arrays, or Dask arrays?

**Comment by rsignell** [comment]
Good to see you here @jrbourbeau! 
* thanks for the tip on the ncfile -- makes sense
* the Xarray dataset returned by process is currently numpy array, but I could add `chunks={}` to make them dask arrays.   Would that be advantageous?

**Comment by rsignell** [comment]
Changed both, and disk usage looks better but still failing:
https://cloud.coiled.io/clusters/367714/information?account=fathom-mgray&tab=Metrics

**Comment by phofl** [comment]
I am seeing some File not found errors, 

```
"FileNotFoundError(2, 'No such file or directory')"
```

Do you want to hop on a call tomorrow to look at this together?

**Comment by rsignell** [comment]
@phofl   Okay, I looked into it and apparently the Open Storage Network pod this data is on is undergoing maintenance/upgrade.   I would love to hop on a call tomorrow and look at this together!   I'm available 9-4pm ET tomorrow.

**Comment by phofl** [comment]
I sent you an email

**Comment by rsignell** [comment]
@phofl helped us get this going -- it involved:
* This PR https://github.com/fsspec/filesystem_spec/pull/1521 @martindurant 
* Loading the data from the output xarray dataset before closing the temporary file!
This is a completely reproducible workflow (no credentials required, and no egress fees!):

1. Use this [conda environment file](https://gist.github.com/rsignell/f756b38216bce88ba4463202cc3960a3) to create conda environments locally and on coiled:
```
mamba env create -f odrift-d7.yml
coiled env create -n odrift-d7 --conda odrift-d7.yml

2.  Run [this notebook](https://nbviewer.org/gist/rsignell/53384c7ce9b40a5432e41dfde1c86c74) locally.
