### ISSUE TITLE
ignore_local_packages in coiled.create_software_environment is ignored

### ISSUE THREAD

**Issue by seanv507** [coiled/feedback#270]
in version 1.3.10, core.py lines 836-841

```
if include_local_code:
                prefix = await scan_prefix()
                packages, _ = partition_ignored_packages(
                    prefix, {(k, "pip"): PackageLevelEnum.IGNORE for k in ignore_local_packages}
                )
                packages, local_packages = partition_local_python_code_packages(prefix)
```
I think last line should be

``` packages, local_packages = partition_local_python_code_packages(packages)``` 

otherwise the `packages` filtering out ignored packages is overwritten

**Comment by dan-blanchard** [comment]
Thanks for catching and reporting this! We'll have a new version with this fix out soon.
