### ISSUE TITLE
Small VM from Step 3 of "Getting started" won't start.

### ISSUE THREAD

**Issue by JesseRuttTX** [coiled/feedback#273]
I am at step 3 of "Getting Started" and I cant get the vm to start up. I try to run the "coiled run echo "Hello, world"" command and it begins to open but gets stuck near the end of the process until it times out. If it is important, I used AWS for the cloud connection.

This is where it gets stuck:

<img width="561" alt="Screenshot 2024-03-27 at 8 21 06 AM" src="https://github.com/coiled/feedback/assets/165169751/50429b72-3aff-4a47-bbe5-c96b93f944ee">

These are the failed attempts I have had to get it started:

<img width="1156" alt="Screenshot 2024-03-27 at 8 11 19 AM" src="https://github.com/coiled/feedback/assets/165169751/ebf98db3-5ae8-4794-96e3-070a24741ba7">

**Comment by dchudz** [comment]
Hi Jesse-- sorry about this! I see that the build is timing out.

I'd like us to figure out why and hopefully figure out a fix on our end (or at least be able to provide more specific advice). But in the meantime:

We often find that when people have a large collection of packages they've built up in their environment over time, and some of those packages that aren't needed anymore are the ones causing problems.

If your local conda environment isn't one you build very recently to use with Coiled, I'd recommend you try making a new environment with just the packages you want for this project.

**Comment by JesseRuttTX** [comment]
Thank you for your quick response. I tried it in a relatively new environment I have and it seems to be working correctly now!

Thank you for your help!
