### ISSUE TITLE
please delete my account

### ISSUE THREAD

**Issue by hotlogical** [coiled/feedback#281]

**Comment by dchudz** [comment]
Hi-- please send an email to support@coiled.io.

Thanks.

**Comment by hotlogical** [comment]
I did - but they didn't delete my account

**Comment by dchudz** [comment]
When did you email? I'm looking for that now. Feel free to email again.

**Comment by mrocklin** [comment]
Just for context, we ask people to e-mail so that we have a message from the e-mail address associated to the account.  This feels mildly safer before we deactivate a user's account.
