### ISSUE TITLE
Is there a way to communicate with all the members of my workspace or org?

### ISSUE THREAD

**Issue by rsignell** [coiled/feedback#293]
Is there a way to communicate with the people in a Coiled workspace?  

I invited members to my Coiled workspace using their email addresses, but I didn't keep track of those email addresses (I invited people live at the ESIP workshop). 

I looked in the interface and couldn't figure out a way to obtain the email addresses or otherwise communicate.

**Comment by dchudz** [comment]
Hey Rich, I'll move to email to discuss this with you.
