### ISSUE TITLE
blog link broken 

### ISSUE THREAD

**Issue by lostmygithubaccount** [coiled/feedback#297]
on this page: https://docs.coiled.io/blog/index.html

this link: https://docs.coiled.io/blog/blog/tpch.html

404s

removing the extra "/blog" takes me to the current TPC-H benchmarking blog, but I was trying to reference (in an Ibis blog) the improvements specifically from moving to Dask expressions:

<img width="825" alt="image" src="https://github.com/user-attachments/assets/9a1da6a5-0ef3-4690-9e3a-5a3e34ba5ee9">

is this blog still something around that could be linked to?

**Comment by jrbourbeau** [comment]
Ah, thanks for catching that @lostmygithubaccount 

cc @scharlottej13 @phofl who will have more context

**Comment by scharlottej13** [comment]
Thanks @lostmygithubaccount!

I can certainly fix that redirect, but I think you'll want to link to https://docs.coiled.io/blog/dask-dataframe-is-fast.html#optimizer for a description of improvements thanks to Dask expressions.

The same post also has performance improvements broken out by dask expressions (optimizer), p2p shuffling, and using pyarrow strings https://docs.coiled.io/blog/dask-dataframe-is-fast.html#id4

Let us know if that helps!

**Comment by lostmygithubaccount** [comment]
that blog is perfect, thanks!

**Comment by scharlottej13** [comment]
Great! Pushed up a PR for the link too, it'll be fixed in our next release.
