### ISSUE TITLE
Add invalid characters to invalid name error message

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#31]
@quasiben ran into an issue when he tried to make a software environment named `"rapids-15.0-foo"` and received a nicely informative error message saying that he could only use ascii letters, hyphens, underscores, and so on.  He ended up not reading this message, but I wonder if we might include a list of invalid characters at the end

```
Your name ....XXXXXXX
Contained invalid characters {"."}
```

**Comment by shughes-uk** [comment]
I think we do an ok job of this now
