### ISSUE TITLE
Edit cluster configurations

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#32]
We should turn back on editing of cluster configurations.

cc @dantheman39

**Comment by FabioRosado** [comment]
We have recently fixed the issue where updating a cluster configuration wouldn't update the software environment field if being passed. We also talked about this issue, it seems that we want users to edit their cluster configuration. 

I'm closing this issue, unless you think the cluster configuration shouldn't be edited? Please reopen the issue if we should talk or modify the behaviour of our `create_cluster_configuration`
