### ISSUE TITLE
GPU Instance pool for RAPIDS-Academy talk

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#36]
Hi @felipeblazing for next week's RAPIDS Academy talk I'd like for us to use whatever architecture you use on app.blazingsql.com .  Can you share details about how you set up your AWS nodes?  What instance type did you use?  What CUDA/RAPIDS version?  Do you happen to have a conda environment handy?

Also more generally I'm curious, how large of a deployment do you all tend to run and how much does that cost you?

cc also @quasiben @necaris

**Comment by roaramburu** [comment]
Hey Matt!

The first version of the app was built on JH, but there is now a lot of custom code around managing servers, users, etc. It's about to have a pretty big refresh where it's all an application of our design, and JH is just a small component of it.

We have two centrally managed conda environments in there (RAPIDS Stable and RAPIDS Nightly) that we can update. If you can give us a list of missing packages for your talk we can get them pre-installed.

It's CUDA 10.2.

RAPIDS Nightly gets updated every night assuming it passes a series of tests we run. 

RAPIDS Stable gets updated at every major release.

**Comment by necaris** [comment]
@roaramburu I don't know if this is what @mrocklin had in mind but as we implement GPUs on Coiled I'd be interested to know:
 - is it correct to assume you're running on EC2? 
 - how you set up your nodes (e.g. instance type, AMI)
 - what packages are in the stable environment

...if you feel comfortable sharing some of those details.

**Comment by mrocklin** [comment]
You all mentioned that you were using T4s, which instance type does this
correspond to?

**Comment by roaramburu** [comment]
Oh I see, we're getting a little bit into our business model territory, so probably not the best place to discuss.

We use AWS G4 instances, but that will actually change soon.

**Comment by mrocklin** [comment]
Yup, no worries.

**Comment by FabioRosado** [comment]
Hello I'm closing some of the open issues in this repository, I'm assuming that the conversation moved somewhere else, so I'm closing this issue 😄
