### ISSUE TITLE
Getting started instructions on Windows don't work

### ISSUE THREAD

**Issue by therriault** [coiled/feedback#42]
Following along the instructions, I get to the login stage but there's no "coiled" executable (or at least it's not in a default path):

TODO: add screenshot

I can obviously fix the yaml file manually to add in the token, but the next step (installing the local software environment) requires this to work.

**Comment by jrbourbeau** [comment]
@therriault thanks for raising an issue! FYI, I removed the image from your original post as I noticed you marked out your user token in one part of the screenshot, but it was still present in the traceback. If you could post a traceback without your token in it, I'd be happy to help debug

**Comment by mrocklin** [comment]
>  I get to the login stage but there's no "coiled" executabl

I ran into this too.  It felt like the `pip install` process was happening (I saw it in logs), but wasn't affecting the given environment.

**Comment by mrocklin** [comment]
Ah, I'm sorry, I only run into this after I run `coiled install coiled/default`.  I have no problem if I've previously  run `pip install coiled`.

**Comment by FabioRosado** [comment]
Hello, I am checking these open issues and closing some of them. I tested installing coiled with conda and pip on windows, and I was able to use the `coiled` command from the terminal. There was an issue with conda that has been solved (xref: #95). 

With this in mind, I am closing this issue, but please feel free to re-open or open a new one if you encounter any further (or new) problems 😄
