### ISSUE TITLE
Support private git repositories when building software environments

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#52]
Coiled currently allows users to include public git repositories in their software environments by including them in their `pip=` requirements

```python
coiled.create_software_environment(
    ..., 
    pip=["git+https://github.com/dask/dask@master"],
)
```

However, sometimes users have software in private git repositories.  Is there a convenient way to support these?

**Comment by mrocklin** [comment]
They're both sensible approaches.  We'll probably enable both in the future.  The easiest things for us to do in order are ...

1.  Optionally expose privacy settings to team accounts
2.  Let you specify a git ssh key for an account, and use that ssh key when building docker images
3.  Let you specify an IAM role for us to use to build and launch things in your account

We'll end up doing all three eventually, but 1 and 2 are moderately easy to do soon.  cc @marcosmoyano for 1, 2 and @dantheman39 for 2 I think.

**Comment by mrocklin** [comment]
Checking in here @jose-moralez .  I thought that you'd like to know that this is in progress.  

Also @marcosmoyano if you wanted to walk through your proposed solution with @jose-moralez , either here or in a call, it might be good to get feedback.

**Comment by marcosmoyano** [comment]
Sure thing! My proposed solution is as follows:
* Users who need access to a private repo should set up a personal access token (https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)
* Add the token to their Coiled user
* When creating a software environment, the format to support pip private repos would be something like `git+https://GIT_TOKEN@github.com/account/repo.git` where GIT_TOKEN is basically a placeholder for your token.
* At software environment creation time, we'll replace the placeholder with the personal access token.

@jose-moralez Let me know if something like this would work for you. Happy to discuss this further either here or in a call.

**Comment by jose-moralez** [comment]
Yeah I use a similar approach in the github action that runs some tests which need to clone one of the repos we use. Would there be like a secrets section in the coiled profile page? I think that would be extremely useful for some other credentials as well like for S3 and databases.

**Comment by marcosmoyano** [comment]
> Would there be like a secrets section in the coiled profile page?

Exactly :+1:

**Comment by shughes-uk** [comment]
We have pretty good support for this now
