### ISSUE TITLE
Quickstart error: missing s3fs

### ISSUE THREAD

**Issue by hugobowne** [coiled/feedback#62]
After @chriscardillo had [this issue](https://github.com/coiled/coiled-issues/issues/61),

he got an error that he was missing s3fs after running

```
import dask.dataframe as dd

df = dd.read_csv(
    "s3://nyc-tlc/trip data/yellow_tripdata_2019-*.csv",
    dtype={
        "payment_type": "UInt8",
        "VendorID": "UInt8",
        "passenger_count": "UInt8",
        "RatecodeID": "UInt8",
    },
    storage_options={"anon": True},
    blocksize="16 MiB",
).persist()
```

from the quickstart.

Any idea why this happened?

**Comment by jrbourbeau** [comment]
Hrm, `s3fs` was added as a dependency for `coiled` starting with `coiled==0.0.19`. What version of `coiled` was installed? If using `coiled>=0.0.19`, are you sure the local environment with `coiled` installed was activated when you ran the quickstart?

**Comment by hugobowne** [comment]
Not sure which version but i watched him pip install coiled < 24 hours ago so it would be the most recent, yeah?

Then everything worked smoothly, except for this error so I presume it was this version. 

We can go back and check the screen share also, which I posted in slack :)

**Comment by chriscardillo** [comment]
Was using version 0.0.22

**Comment by hugobowne** [comment]
> are you sure the local environment with coiled installed was activated when you ran the quickstart?

I thought it must have been as `import coiled` worked.

It was quickstart Step 3 that threw the error

**Comment by FabioRosado** [comment]
With the latest coiled changes, the default software environments have the `s3fs` dependency, which will fix this issue. I've also tested this by running the quickstart, and everything worked as we expect 👍
