### ISSUE TITLE
Patterns in first questions about Coiled

### ISSUE THREAD

**Issue by hugobowne** [coiled/feedback#63]
I've noticed the following questions in both product discovery and user experience calls (the latter are where I watch someone log in to Beta and try to get a cluster up and running).

Common questions:

- Where is the cluster?
_ Who owns the cluster?
- Who is paying for it? (or "It appears I don't have to pay?")
- How do I shut it down?

Could we answer these in a few words on the quick start page?

Any other suggestions?

FWIW, I don't think the [FAQ](https://docs.coiled.io/user_guide/faq.html) is the answer to these concerns as to get there, users need to leave beta.coiled.io and have less chance of coming back to quickstart.

**Comment by dantheman39** [comment]
As of today the "stop" button is back in the UI, which can be used to stop a cluster, and I believe `cluster.close()` is the API way? Would be good to mention in the docs.

**Comment by FabioRosado** [comment]
It seems that out of all these questions, perhaps the one that we still need to answer is "how I shut it down" on the quick start? Should we update it to mention how someone can stop a cluster so we can close this issue? 🤔

**Comment by shughes-uk** [comment]
Seems to be reasonably resolved by our current material
