### ISSUE TITLE
Add account-level credentials / environment variables

### ISSUE THREAD

**Issue by mrocklin** [coiled/feedback#69]
It would be useful to associate credentials to a specific account.  This can help users connect to secure resources, like databases.  

My guess is that the easiest way to do this is through environment variables.  On the Account profile page we could have a table of current environment variables (probably with hidden values by default).  These environment variables would be set whenever we make a new ECS task, either with clusters or jobs.

Eventually we may also want to associate these credentials / environment variables with users, but I think that starting with accounts will give us enough to make people happy.

**Comment by shughes-uk** [comment]
Added and then deprecated
