### ISSUE TITLE
Inconsistency in author-wise collection of blog posts

### ISSUE THREAD

**Issue by pavithraes** [coiled/feedback#71]
Tiny inconsistency in the [blog](https://coiled.io/blog/), the posts by David Venturi don't seem to collect at the same place. The three posts are collected under 3 different "author names":
* https://coiled.io/blog/author/david/.
* https://coiled.io/blog/author/david-venturi-2/
* https://coiled.io/blog/author/david-venturi/

I'm not sure if this is the right place to report this. If it isn't, please point me in the right direction.

**Comment by jrbourbeau** [comment]
Nice catch, thanks for pointing that out @pavithraes! cc @hugobowne

**Comment by shughes-uk** [comment]
We've changed our blog software since this so i'm assuming this is not longer relevant
