### ISSUE TITLE
Connecting to existing cluster outside default region fails

### ISSUE THREAD

**Issue by necaris** [coiled/feedback#74]
/cc @quasiben

When connecting to an existing cluster with `coiled.Cluster(name="foo")`, it errors with:
```
Creating Cluster. This takes about a minute ...A running cluster exists with the same name. Did you want to connect to the cluster instead?
```
when connecting to the existing cluster is _exactly_ what's wanted. It turns out that passing the `region=` argument is needed; this should be in the docs (or ideally, be unnecessary) :smile:

**Comment by mrocklin** [comment]
cc also @marcosmoyano

**Comment by marcosmoyano** [comment]
I think this is something that should be reflected in the docs since having two clusters with the same name on two different regions is possible. The region then becomes the differential factor.

**Comment by FabioRosado** [comment]
Hello, I've tested this issue with:

```python
cluster_one = coiled.Cluster(name="test-region", backend_options={"region": "us-west-1"})
# wait for cluster to spin up
cluster_two = coiled.Cluster(name="test-region", backend_options={"region": "us-east-2"})
```

And got the message: "Using existing cluster: test-region". After speaking with Rami, we might want to do one of the two:

- Throw an error if a cluster is found but on a different region
- Create the cluster with the same name in a different region (having two clusters with the same name running)

I'm just updating this issue and perhaps spark some discussion as to what would be better to do here 😄

**Comment by shughes-uk** [comment]
fixed
