### ISSUE TITLE
Installing coiled into an existing conda environment

### ISSUE THREAD

**Issue by ericdill** [coiled/feedback#9]
Installing into an existing conda environment proved challenging. What are the listed requirements? Ended up having to extract the tarball from pypi and check `coiled_cloud.egg-info/requires.txt`:

```
aiohttp 
aiobotocore<0.13,>=0.12.0 
distributed 
```

Suggested fix: Include the requirements in the readme so it renders properly on pypi. Bonus: Tell me exactly what I need to put in my environment.yml file:
```
- aiobotocore<0.13,>=0.12.0
- distributed
- pip
- pip:
    - coiled-cloud
```

 :rocket: Double bonus: release on conda-forge :grin: :rocket:

**Comment by necaris** [comment]
@ericdill Those are great suggestions, thank you! FWIW, conda-forge is on our to-do list -- hoping to clear up a few things like the ones you're reporting first :-)

**Comment by jrbourbeau** [comment]
> 🚀 Double bonus: release on conda-forge 😁 🚀

We added `coiled-cloud` to conda-forge (https://anaconda.org/conda-forge/coiled-cloud)! This should help with installing into existing conda environments

**Comment by FabioRosado** [comment]
Hello, I'm going through the open issues on this repository and closing some of them. I'm assuming that by downloading coiled from conda forge, it will fix the issue. 

I'm closing this, but feel free to re-open or open a new issue with any problems you might have 😄
